package pro.turnoworld.quests;

public enum QuestType {
    BREAK, PLACE, KILL, CRAFT, SMELT, FISH, BREED, TAME, SHEAR, CONSUME,
    ENCHANT, SLEEP, WALK, PLAYTIME, VISIT_WORLD, VISIT_BIOME, ADVANCEMENT,
    DAMAGE, BLOCK_DAMAGE, DELIVER
}
